# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

language: node_js
node_js: 10

cache: npm

jobs:
  include:
    - name: "Run Truffle tests (Ganache)"
      env: CI=true
      script:
        - make install-celo-ganache
        - SILENT=true make celo-ganache
        - make test

    - name: "Run coverage"
     script:
       - ./node_modules/.bin/truffle run coverage -solcoverjs ./scripts/.solcover.js --network test
       - cat ./coverage/lcov.info | node_modules/.bin/coveralls
