# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install ganache
        run: make install-celo-ganache
      - name: Start celo-ganache
        run: SILENT=true make celo-ganache
      - name: Test
        run: make test
      - name: Run coverage
        run: ./node_modules/.bin/truffle run coverage -solcoverjs ./scripts/.solcover.js --network test
      - name: Cover
        run: echo ::set-env name=COVERAGE::$(cat ./coverage/lcov.info | node_modules/.bin/coveralls)
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.number}}
          body: |
            Test coverage is ${{ env.COVERAGE }}% :sparkles: :sparkles: :sparkles:

