name: Run tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set env
        run: echo $PATH
      - name: install celo ganache
        run: |
          git clone --depth 1 https://github.com/celo-org/ganache-cli.git
          npm install --prefix ./ganache-cli
          ln -f -s  $PWD/ganache-cli/cli.js  /usr/local/bin/celo-ganache

      - name: Start celo-ganache
        run: celo-ganache -q --blockTime 1 -p $PORT --account "0x000000000000000000000000000000000000000000000000000000616c696365,100000000000000000000" --account "0x0000000000000000000000000000000000000000000000000000000000626f62,100000000000000000000" --account "0x00000000000000000000000000000000000000000000000000636861726c6965,100000000000000000000"  --account "0x0000000000000000000000000000000000000000000000000000000064617665,100000000000000000000" --account "0x0000000000000000000000000000000000000000000000000000000000657665,100000000000000000000"
      - name: Waiting for ganache to start
        run: sleep 3
      - name: Test
        run: make test
      - name: Run coverage
        run: ./node_modules/.bin/truffle run coverage -solcoverjs ./scripts/.solcover.js --network test
      - name: Cover
        run: echo ::set-env name=COVERAGE::$(cat ./coverage/lcov.info | node_modules/.bin/coveralls)
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.number}}
          body: |
            Test coverage is ${{ env.COVERAGE }}% :sparkles: :sparkles: :sparkles:

